# Generated by Django 3.0 on 2020-02-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Längden kommer att synas i dina spelarprofiler. Ange längden i cm.', null=True, verbose_name='längd'),
        ),
    ]
