# Generated by Django 3.0 on 2020-02-14 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_auto_20200213_1604'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.IntegerField(unique=True)),
                ('sport', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField(max_length=500, verbose_name='beskrivning')),
                ('max_age', models.PositiveIntegerField(verbose_name='ålder')),
                ('min_height', models.PositiveIntegerField(verbose_name='längd')),
                ('min_experience', models.CharField(max_length=255, verbose_name='erfarenhet')),
                ('special_ability', models.CharField(max_length=255, verbose_name='spetsegenskap')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='players.Position')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['ad_id'], name='ads_ad_ad_id_098d47_idx'),
        ),
    ]
