# Generated by Django 3.0 on 2020-02-13 16:04

from django.db import migrations, models
import hittalaget.teams.models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, default='images/teams/default.png', null=True, upload_to=hittalaget.teams.models.get_upload_path),
        ),
    ]
