# Generated by Django 3.0 on 2020-02-10 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hittalaget.players.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('sport', models.CharField(choices=[('fotboll', 'Fotboll')], max_length=255)),
                ('side', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('special_ability', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='images/players/default.png', null=True, upload_to=hittalaget.players.models.get_upload_path)),
                ('positions', models.ManyToManyField(related_name='players', to='players.Position')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
                ('team_name', models.CharField(max_length=255)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='players.Player')),
            ],
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('user', 'sport'), name='unique player'),
        ),
    ]
